/* Chime Health — Choose Your Treatment V6 = the GLP + Tesamorelin Deep Belly Burn product selection, VERSION 1 of
   the client doc "glp plus tesa.docx" (2026-09-29: "EXACT SAME VERSIONS AND PAGES AS THE ONE YOU DID FOR THE GLP + NAD,
   ALL WE WILL BE DOING IS SWAPPING OUT THE NAD FOR TESAMORELIN"): chime-get-started-glp-tesa → v6.html (v7.html by its
   own link) → checkout-v6/. plans-data-v4.js (the GLP + NAD+ V4) with the swaps: Tirzepatide = "Deep Belly Burn Plus"
   ("Compounded Tirzepatide and Tesamorelin - in one plan"), Semaglutide = "Deep Belly Burn" ("Compounded Semaglutide and
   Tesamorelin - in one plan"), each shown as its vial + the amber Tesamorelin vial; checkout "Deep Belly Burn Plan" /
   "Deep Belly Burn Plus Plan", "+ FREE Tesamorelin ($299 value)", coupon FREETESA, "BONUS: Tesamorelin - both products,
   one price" ~~$299~~ FREE. Prices, plans and checkout maths are V4's, unchanged:
     Deep Belly Burn Plus  6M $249 / month, $1,494 due today - save $660 · 3M $299, $897 - save $180 · monthly $359
     Deep Belly Burn       6M $199 / month, $1,194 due today - save $600 · 3M $249, $747 - save $150 · monthly $299
   Loaded by v6.html and checkout-v6/index.html. Generated by uploads/get-started-wl-ref/glp_tesa_select.py. */
(function (root) {
  var DATA = {
    heroPlan: null,
    rowPlans: ['sixMonth', 'threeMonth', 'monthly'],
    checkoutHref: 'checkout-v6/',
    productHref: '../v6.html',
    checkoutOffer: {
      badge: '+ FREE Tesamorelin ($299 value)',
      code: 'FREETESA',
      bonusLabel: 'BONUS: Tesamorelin - both products, one price',
      bonusValue: 299,
      removedLabel: 'Tesamorelin',
      pairAlt: 'GLP-1 and Tesamorelin vials',
      images: { tirz: 'images/tirzepatide-tesa-amber.webp', sema: 'images/semaglutide-tesa-amber.webp' }
    },
    urgency: { discountsLeft: 5, minutes: 6, seconds: 57 },
    press: ['Forbes', 'USA TODAY'],
    rating: { value: '4.7', full: 4, half: 1 },
    nextSteps: [
      { icon: '📋', lines: ['Clinician', 'Review'], note: 'Within 24 hours' },
      { icon: '📦', lines: ['Medication', 'Ships'], note: 'Free delivery' },
      { icon: '💬', lines: ['Ongoing', 'Support'], note: "We're here for you" }
    ],
    treatments: [
      {
        id: 'injectable-tirzepatide',
        key: 'tirz',
        name: 'Deep Belly Burn Plus',
        nameWraps: true,
        cardTitle: 'Deep Belly Burn Plus',
        checkoutName: 'Deep Belly Burn Plus Plan',
        recommendedLabel: 'For those looking to lose 20+lbs',
        tagline: 'Compounded Tirzepatide and Tesamorelin - in one plan',
        highlights: ['Strongest appetite suppression', 'Fastest results'],
        badgeLabel: 'Fastest Results',
        badgeIcon: 'bolt',
        accent: 'gold',
        patientsToday: 17482,
        image: 'images/tirzepatide-tesa.webp',
        plans: {
          sixMonth: {
            months: 6, label: '6-MONTH PLAN', price: 249, totalPrice: 1494, savingsToday: 660,
            checkout: { crossed: 2154, termLabel: '6 Months' },
            features: ['Highest long-term success', 'Preferred by patients who want to lose 10%+ of body weight', 'Price stays the same regardless of dosage']
          },
          threeMonth: {
            months: 3, label: '3-MONTH PLAN', price: 299, totalPrice: 897, savingsToday: 180,
            checkout: { crossed: 1077, termLabel: '3 Months' },
            features: ['Same medications, same care', 'Fewer shipments', 'Better consistency', 'Same price regardless of dosage']
          },
          monthly: {
            months: 1, label: 'MONTHLY PLAN', sublabel: 'Pause or Cancel anytime', price: 359, totalPrice: 359,
            checkout: { crossed: 359, termLabel: 'Monthly' },
            features: ['Same price every month — no increases ever', 'Same price regardless of dose', 'Physician-guided dosing, adjusted as needed'],
            footerNote: 'No surprises. No step-ups. No dosage-based pricing.'
          }
        }
      },
      {
        id: 'injectable-semaglutide',
        key: 'sema',
        name: 'Deep Belly Burn',
        nameWraps: true,
        cardTitle: 'Deep Belly Burn',
        checkoutName: 'Deep Belly Burn Plan',
        recommendedLabel: 'For those looking to lose up to 20lbs',
        tagline: 'Compounded Semaglutide and Tesamorelin - in one plan',
        highlights: ['Proven GLP-1 appetite control', 'Lower starting cost'],
        badgeLabel: 'Most Affordable',
        badgeIcon: 'clock',
        accent: 'green',
        patientsToday: 11251,
        image: 'images/semaglutide-tesa.webp',
        plans: {
          sixMonth: {
            months: 6, label: '6-MONTH PLAN', price: 199, totalPrice: 1194, savingsToday: 600,
            checkout: { crossed: 1794, termLabel: '6 Months' },
            features: ['Highest long-term success', 'Preferred by patients focused on sustainable weight loss', 'No monthly billing during your plan, ever']
          },
          threeMonth: {
            months: 3, label: '3-MONTH PLAN', price: 249, totalPrice: 747, savingsToday: 150,
            checkout: { crossed: 897, termLabel: '3 Months' },
            features: ['Same medication, same care', 'Fewer shipments', 'Better consistency', 'Same price regardless of dosage']
          },
          monthly: {
            months: 1, label: 'MONTHLY PLAN', sublabel: 'Pause or Cancel anytime', price: 299, totalPrice: 299,
            checkout: { crossed: 299, termLabel: 'Monthly' },
            features: ['Same price every month — no increases ever', 'Same price regardless of dose', 'Physician-guided dosing, adjusted as needed'],
            footerNote: 'No surprises. No step-ups. No dosage-based pricing.'
          }
        }
      }
    ]
  };
  root.CHIME_CHOOSE_TREATMENT = DATA;
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA;
})(typeof window !== 'undefined' ? window : globalThis);
