/*
 * quiz-logic.js  (GLPQuizFR)
 *
 * The disqualification engine. Ported from GLPQuizTR's js/quiz-logic.js, which is
 * the funnel this one is being brought to parity with (Devin msg 1892: "TR language
 * is preferred as is logic, and answers from questions").
 *
 * WHAT IS PORTED, AND WHAT IS NOT
 *
 * Ported, semantics intact: the DQ table keyed by page, the SAFE-list inversion for
 * multi-selects, the exclusive "none of these" option and its auto-advance, the
 * conditional reveal blocks and the clearHidden distinction, the two age/BMI bands
 * and the consent boxes they gate, the disqualify-before-validate ordering, and the
 * ?back=&next= contract with disqualified.html.
 *
 * NOT ported: TR's storage layer. TR keeps one localStorage blob under "glpquiz"
 * keyed form[whatever]. This funnel already writes flat sessionStorage keys from each
 * page's own inline script (dob, state, gender, heightFeet, heightInches,
 * weightInPounds), and the age/BMI rule reads exactly those four. Rewriting FR's
 * storage to match TR's would have meant rewriting step1 and step3 for no gain and
 * some risk, so the accessors below read FR's keys and everything above them is TR's.
 *
 * ONE DELIBERATE IMPROVEMENT OVER TR. TR stores BMI as a string on step1
 * (form[bmi], toFixed(2)) and the bands read it back. A stored derived value can go
 * stale against the height and weight it came from. Here BMI is computed on demand
 * from the three inputs, then rounded to two decimals, because the bands were written
 * against a two-decimal number: see adultNeedsMetabolicConsent below, where the
 * difference between b < 23 and b <= 22.9 was a real bug in TR.
 *
 * The pages step4 through step14 and disqualified.html are GENERATED by
 * scripts/build/pages.mjs from scripts/build/plan.mjs. The group and reveal
 * attributes this file reads are emitted there. Do not hand-edit those pages.
 */
(function () {
  "use strict";

  // Where "Keep Answer" sends a disqualified visitor: the landing page, in the language
  // they were reading. The English funnel lives in questionnaire/ and the Spanish mirror
  // in questionnaire/es/, so the exit is one directory up from one and two from the other.
  //
  // A constant "../index.html" resolves to questionnaire/index.html on the Spanish page,
  // which is a 404. Computed here rather than hardcoded per tree, because the two trees
  // are generated from one source and a per-tree constant could only be injected at build
  // time, which is a place a bug can hide.
  function inEsDir() {
    var p = location.pathname;
    return /\/es\/$/.test(p.slice(0, p.lastIndexOf("/") + 1));
  }
  var EXIT_URL = inEsDir() ? "../../index.html" : "../index.html";
  var DQ_PAGE = "disqualified.html";

  // The last screening page. Nothing after this can disqualify anybody.
  var LAST_STEP = 19;

  // Ticking the exclusive option also auto-advances (TR, Devin msg 1714). The delay
  // lets the checkbox paint as ticked before the page navigates; without it the click
  // reads as unresponsive. Exposed so the verify walkers can wait on it rather than
  // race a hardcoded sleep.
  var EXCLUSIVE_ADVANCE_MS = 400;
  window.__quizExclusiveAdvanceMs = EXCLUSIVE_ADVANCE_MS;

  // -------------------------------------------------------------------------
  // Storage. Flat sessionStorage keys, the convention every existing page in this
  // funnel already uses. A multi-select stores a JSON array of the checkbox VALUES.
  //
  // The value of a condition checkbox IS its GLPQuizTR answer text, which is what
  // the safe lists below match on. The numeric CRM id that FR used to store lives on
  // as a data-crm-id attribute (Devin msg 1892 answer C: nothing is coming from the
  // CRM, so no new id may be invented, and no existing one may be lost).
  // -------------------------------------------------------------------------
  function get(k) {
    try { return sessionStorage.getItem(k); } catch (e) { return null; }
  }
  function set(k, v) {
    try { sessionStorage.setItem(k, v); } catch (e) {}
  }
  function del(k) {
    try { sessionStorage.removeItem(k); } catch (e) {}
  }
  function getArr(k) {
    try {
      var v = JSON.parse(get(k) || "[]");
      return Array.isArray(v) ? v : [];
    } catch (e) { return []; }
  }

  function currentFile() {
    var p = (location.pathname.split("/").pop() || "index.html").split("?")[0];
    return p === "" ? "index.html" : p;
  }

  // A GENERATED page (step4 through step14) marks its <main data-quiz-owned>. This
  // file supplies its navigation, its restore and its whole validation.
  //
  // step3 and step16 are NOT owned. They were written by the funnel's original authors,
  // they restore and validate their own fields, and they own their own Continue click.
  // On those two pages this file adds exactly two things and touches nothing else: the
  // consent boxes it injected, and (on step3) the age/BMI disqualifier. Validating the
  // whole document there would stomp the inline scripts' own field-level error copy
  // with a generic toast, which is a regression, not a gate.
  function owned() {
    return !!document.querySelector("[data-quiz-owned]");
  }

  function consentBoxes() {
    return document.querySelectorAll("[data-consent-block] input[type=checkbox][name]");
  }

  // An element counts as visible only if it renders. Hidden reveal blocks and hidden
  // consent boxes must never gate the Continue button.
  function visible(el) {
    return !!(el.offsetWidth || el.offsetHeight || el.getClientRects().length);
  }

  function groupOf(el) {
    return el.closest("[data-group]");
  }

  // -------------------------------------------------------------------------
  // Capture. Pulls whatever is on this page into storage.
  // -------------------------------------------------------------------------
  // On an unowned page this writes ONLY the consent boxes. step3 and step16 already
  // persist their own fields under these same keys from their own input listeners, and
  // writing them twice from two places is how the two copies drift.
  function capture() {
    var els = owned()
      ? document.querySelectorAll("input[name], select[name], textarea[name]")
      : consentBoxes();
    var arrays = {};

    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      if (el.type === "submit" || el.type === "button" || el.type === "reset") continue;

      if (el.type === "checkbox") {
        var g = groupOf(el);
        if (g && g.getAttribute("data-multi") === "true") {
          if (!(el.name in arrays)) arrays[el.name] = [];
          if (el.checked) arrays[el.name].push(el.value);
          continue;
        }
        // A standalone checkbox is a consent. An unchecked box is ABSENT, not empty:
        // a consent that was ticked and then hidden must leave nothing behind that
        // could later read as agreement.
        if (el.checked) set(el.name, el.value || "on");
        else del(el.name);
        continue;
      }

      if (el.type === "radio") {
        if (el.checked) set(el.name, el.value);
        continue;
      }

      if (String(el.value).trim() !== "") set(el.name, el.value);
    }

    for (var name in arrays) {
      if (arrays[name].length) set(name, JSON.stringify(arrays[name]));
      else del(name);
    }
  }

  // -------------------------------------------------------------------------
  // Age and BMI.
  // -------------------------------------------------------------------------
  function ageOf() {
    var m = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(String(get("dob") || "").trim());
    if (!m) return NaN;
    var mo = parseInt(m[1], 10), da = parseInt(m[2], 10), yr = parseInt(m[3], 10);
    var now = new Date();
    var age = now.getFullYear() - yr;
    var thisMonth = now.getMonth() + 1;
    // Birthday has not landed yet this year.
    if (thisMonth < mo || (thisMonth === mo && now.getDate() < da)) age--;
    return age;
  }

  // step3 collects heightFeet, heightInches and weightInPounds. Same formula as
  // js/warm-up-bmi.js, which prints the number to the visitor.
  //
  // Rounded to two decimals ON PURPOSE. The bands were written against a two-decimal
  // BMI (see adultNeedsMetabolicConsent). Do NOT round to one decimal to "tidy" it:
  // that rounds 22.96 up to 23.0 and sends the heavier patient straight through, which
  // is the bug this comment exists to prevent, inverted.
  function bmiOf() {
    var ft = parseFloat(get("heightFeet"));
    var inch = parseFloat(get("heightInches"));
    var lbs = parseFloat(get("weightInPounds"));
    if (isNaN(ft) || isNaN(lbs) || ft <= 0 || lbs <= 0) return NaN;
    if (isNaN(inch)) inch = 0;
    var totalInches = ft * 12 + inch;
    if (totalInches <= 0) return NaN;
    return parseFloat(((703 * lbs) / (totalInches * totalInches)).toFixed(2));
  }

  // 65+ splits two ways (TR, Devin msgs 1693/1695):
  //   BMI < 22  -> disqualified (too little reserve for rapid weight loss)
  //   BMI >= 22 -> continue, after acknowledging the elderly consent
  function elderlyLowBmi() {
    var a = ageOf(), b = bmiOf();
    return a >= 65 && !isNaN(b) && b < 22;
  }
  function elderlyNeedsConsent() {
    var a = ageOf(), b = bmiOf();
    return a >= 65 && !isNaN(b) && b >= 22;
  }

  // Adults 18 through 64 split three ways (TR, Devin msgs 1714/1721). Age exactly 65
  // belongs to the elderly rules above, never to these, so the two bands cannot both
  // fire and at most one consent box is ever shown.
  //   BMI < 20        -> disqualified
  //   20 <= BMI < 23  -> continue, after acknowledging the metabolic consent
  //   BMI >= 23       -> straight through, no consent
  //
  // TR wrote the consent test as `b <= 22.9` while BMI is stored to two decimals, so
  // 22.91 through 22.99 got neither the consent nor the disqualification. Devin's rule
  // (msg 1757) is "22.99 and below requires consent", which is exactly `b < 23`.
  function isAdultBand() {
    var a = ageOf();
    return a >= 18 && a <= 64;
  }
  function adultLowBmi() {
    var b = bmiOf();
    return isAdultBand() && !isNaN(b) && b < 20;
  }
  function adultNeedsMetabolicConsent() {
    var b = bmiOf();
    return isAdultBand() && !isNaN(b) && b >= 20 && b < 23;
  }

  // -------------------------------------------------------------------------
  // The eight disqualifiers, exactly the eight GLPQuizTR ships, each firing on the
  // submit of the page that asked its question (Devin msg 1884 answer 1).
  //
  // Multi-selects are expressed as a SAFE list rather than a disqualifying one:
  // "everything except these" is what the clinical rule actually says, so a condition
  // added to a page tomorrow disqualifies by default instead of silently passing.
  // Fail closed.
  // -------------------------------------------------------------------------
  var DQ = {
    // Not an answer a visitor picks: a rule over age and BMI, both known by the end
    // of step3. This is the funnel's FIRST disqualifier.
    "step3.html": {
      test: function () { return elderlyLowBmi() || adultLowBmi(); }
    },
    "step4.html": {
      field: "femaleHealthStatus", multi: true,
      safe: ["None of the above"]
    },
    "step5.html": {
      field: "healthConditions", multi: true,
      safe: ["None of these"]
    },
    "step6.html": {
      field: "healthConditionsAdditional", multi: true,
      // Type 2 diabetes NOT on insulin is allowed through; on insulin is not.
      safe: ["None of the below", "Type 2 diabetes (not on insulin)"]
    },
    "step9.html": {
      field: "glp1Allergies", multi: true,
      safe: ["I am NOT allergic to any of these medications"]
    },
    "step10.html": {
      field: "currentGlucoseMedications", multi: true,
      safe: ["I am NOT on any of these medications"]
    },
    "step12.html": {
      field: "takenPainMedicationsOrStreetDrugs", multi: false, dqValues: ["Yes"]
    },
    "step13.html": {
      field: "gastricBypass6Months", multi: false, dqValues: ["Yes"]
    }
  };

  function disqualifies(file) {
    var rule = DQ[file];
    if (!rule) return false;
    if (rule.test) return rule.test();
    if (rule.multi) {
      var v = getArr(rule.field);
      if (!v.length) return false;
      for (var i = 0; i < v.length; i++) {
        if (rule.safe.indexOf(v[i]) < 0) return true;
      }
      return false;
    }
    return rule.dqValues.indexOf(get(rule.field)) >= 0;
  }

  // -------------------------------------------------------------------------
  // Exclusivity. "None of these" cannot coexist with a real condition; without this
  // the form happily submits a contradiction.
  //
  // Exclusivity is a property of the OPTION, not of disqualification, so it is read
  // off the group's own data-exclusive attribute rather than the DQ table. TR learned
  // this the hard way: its pages with a none-option but no disqualifier got neither
  // the exclusivity nor the auto-advance.
  // -------------------------------------------------------------------------
  function bindExclusive() {
    var groups = document.querySelectorAll("[data-group][data-exclusive]");
    for (var i = 0; i < groups.length; i++) {
      (function (group) {
        var none = group.getAttribute("data-exclusive");
        var boxes = group.querySelectorAll('input[type="checkbox"]');
        var timer = null;

        for (var j = 0; j < boxes.length; j++) {
          boxes[j].addEventListener("change", function () {
            // Any further interaction cancels a pending auto-advance. Without this,
            // ticking "None" and then changing your mind inside the delay window
            // still navigates you off the page: the timer was already armed.
            if (timer) { clearTimeout(timer); timer = null; }
            if (!this.checked) { capture(); return; }

            var isNone = this.value === none;
            for (var k = 0; k < boxes.length; k++) {
              if (boxes[k] === this) continue;
              if (isNone || boxes[k].value === none) boxes[k].checked = false;
            }
            capture();

            // Only the exclusive option advances. Ticking a real condition leaves the
            // visitor on the page to keep picking.
            if (isNone) timer = setTimeout(advance, EXCLUSIVE_ADVANCE_MS);
          });
        }
      })(groups[i]);
    }
  }

  // -------------------------------------------------------------------------
  // Routing. Only one branch exists: the female-only screen.
  // -------------------------------------------------------------------------
  function nextFor(file) {
    if (file === "step3.html") return get("gender") === "female" ? "step4.html" : "step5.html";

    var m = file.match(/^step(\d+)\.html$/);
    if (m) {
      var n = parseInt(m[1], 10);
      if (n >= 1 && n < LAST_STEP) return "step" + (n + 1) + ".html";
    }
    return null;
  }

  // step3's Continue is an <a href>, and its own inline script reads that href at
  // click time. Rewriting the href IS the routing, so the branch needs no
  // interception. Recomputed on pageshow because a history navigation can restore a
  // different gender than the one the page loaded with.
  function syncBranchLinks() {
    var file = currentFile();
    var next = nextFor(file);
    if (!next) return;
    var cont = document.getElementById("step3Continue") || document.getElementById("continueBtn");
    if (cont && cont.tagName === "A" && file === "step3.html") cont.setAttribute("href", next);
  }

  // -------------------------------------------------------------------------
  // Conditional reveal blocks.
  //
  // `clearHidden` says whether hiding a block should also erase what it holds. TRUE
  // when the visitor just changed the controlling answer, FALSE on page load. Both
  // directions matter:
  //   - On a change, the block must be cleared BY NAME. Otherwise a returning visitor
  //     who switches to "No" keeps the old text, and the record affirms "no known drug
  //     allergies" while still carrying medicationAllergiesInfo.
  //   - On load, nothing may be cleared at all. Clearing here would wipe the
  //     medications a returning "Yes" visitor already gave us.
  // -------------------------------------------------------------------------
  function valueOf(name) {
    var els = document.querySelectorAll('[name="' + name + '"]');
    for (var i = 0; i < els.length; i++) {
      if (els[i].type === "radio" || els[i].type === "checkbox") {
        if (els[i].checked) return els[i].value;
      } else if (els[i].value !== "") {
        return els[i].value;
      }
    }
    return "";
  }

  function syncReveals(clearHidden) {
    var blocks = document.querySelectorAll("[data-reveal-when]");
    for (var i = 0; i < blocks.length; i++) {
      var b = blocks[i];
      var show = valueOf(b.getAttribute("data-reveal-when")) === b.getAttribute("data-reveal-value");
      b.hidden = !show;
      if (show || !clearHidden) continue;

      var fields = b.querySelectorAll("textarea, input, select");
      for (var j = 0; j < fields.length; j++) {
        fields[j].value = "";
        if (fields[j].name) del(fields[j].name);
      }
    }
  }

  // Restore what storage already holds into this page's controls. On a page this file
  // does not own, only the consent boxes it injected are its to restore.
  function restore() {
    var els = owned()
      ? document.querySelectorAll("input[name], select[name], textarea[name]")
      : consentBoxes();
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      if (el.type === "submit" || el.type === "button" || el.type === "reset") continue;

      if (el.type === "checkbox") {
        var g = groupOf(el);
        if (g && g.getAttribute("data-multi") === "true") {
          el.checked = getArr(el.name).indexOf(el.value) >= 0;
        } else {
          el.checked = get(el.name) !== null;
        }
      } else if (el.type === "radio") {
        el.checked = get(el.name) === el.value;
      } else {
        var v = get(el.name);
        if (v !== null) el.value = v;
      }
    }
  }

  // -------------------------------------------------------------------------
  // Consent boxes (step3). While visible a consent checkbox carries `required`, so
  // validate() gates Continue on it; while hidden it is unchecked and its key deleted,
  // so a stale acknowledgement can never travel with the record.
  //
  // The two age bands are disjoint, so at most one box is ever visible. Rather than
  // trust that, each is evaluated independently and the one that does not apply is
  // hidden AND cleared, which makes "both visible" unrepresentable.
  // -------------------------------------------------------------------------
  function syncConsentBox(boxId, cbId, key, show) {
    var box = document.getElementById(boxId);
    if (!box) return;
    box.hidden = !show;
    if (show) return;
    var cb = document.getElementById(cbId);
    if (cb && cb.checked) {
      cb.checked = false;
      del(key);
    }
  }

  function syncConsents() {
    if (!document.getElementById("elderly-consent") && !document.getElementById("metabolic-consent")) return;
    syncConsentBox("elderly-consent", "form_elderly_consent", "elderly_consent", elderlyNeedsConsent());
    syncConsentBox("metabolic-consent", "form_metabolic_consent", "metabolic_consent", adultNeedsMetabolicConsent());
  }

  // -------------------------------------------------------------------------
  // Validation. Only VISIBLE fields count, so a hidden reveal block or a hidden
  // consent never blocks Continue.
  // -------------------------------------------------------------------------
  // A visible consent checkbox that carries `required` must be ticked. A box carrying
  // data-optional never gates Continue: the SMS consent is not a condition of purchase,
  // and gating on it would be a TCPA problem, not a UX one. This is the ONLY check this
  // file performs on a page it does not own.
  function validateConsents() {
    var boxes = consentBoxes();
    for (var i = 0; i < boxes.length; i++) {
      if (!visible(boxes[i]) || boxes[i].hasAttribute("data-optional")) continue;
      if (boxes[i].hasAttribute("required") && !boxes[i].checked) {
        return "Please read and acknowledge the statement above to continue";
      }
    }
    return "";
  }

  function validate() {
    var i;

    // 1. Every visible radio group must have a selection.
    var radios = document.querySelectorAll("input[type=radio][name]");
    var groups = {};
    for (i = 0; i < radios.length; i++) {
      if (!visible(radios[i])) continue;
      if (!(radios[i].name in groups)) groups[radios[i].name] = false;
      if (radios[i].checked) groups[radios[i].name] = true;
    }
    for (var g in groups) if (!groups[g]) return "Please choose an option to continue";

    // 2. A checkbox carrying `required` must be checked. A checkbox carrying
    //    data-optional never gates Continue: the SMS consent is not a condition of
    //    purchase, and gating on it would be a TCPA problem, not a UX one.
    var checks = document.querySelectorAll("input[type=checkbox][name]");
    for (i = 0; i < checks.length; i++) {
      if (!visible(checks[i]) || checks[i].hasAttribute("data-optional")) continue;
      if (checks[i].hasAttribute("required") && !checks[i].checked) {
        return "Please read and acknowledge the statement above to continue";
      }
    }

    // 3. Each visible multi-select group needs at least one box ticked.
    //    ("None of these" is a valid pick.)
    var multi = {};
    for (i = 0; i < checks.length; i++) {
      var grp = groupOf(checks[i]);
      if (!visible(checks[i]) || !grp || grp.getAttribute("data-multi") !== "true") continue;
      if (!(checks[i].name in multi)) multi[checks[i].name] = false;
      if (checks[i].checked) multi[checks[i].name] = true;
    }
    for (var mg in multi) if (!multi[mg]) return "Please select at least one option to continue";

    // 4. Visible required selects must be answered.
    var sels = document.querySelectorAll("select[required]");
    for (i = 0; i < sels.length; i++) {
      if (!visible(sels[i])) continue;
      if (!String(sels[i].value).trim()) return "Please answer every question to continue";
    }

    // 5. A revealed free-text box must not be left empty.
    var reveals = document.querySelectorAll("[data-reveal-required]");
    for (i = 0; i < reveals.length; i++) {
      if (!visible(reveals[i])) continue;
      if (!String(reveals[i].value).trim()) return "Please fill in the details you were asked for";
    }

    return "";
  }

  function flash(msg) {
    var id = "quiz-logic-flash";
    var el = document.getElementById(id);
    if (!el) {
      el = document.createElement("div");
      el.id = id;
      el.setAttribute("role", "status");
      // pointer-events:none is load bearing, not polish. The toast is fixed just above
      // the sticky footer, so without it the toast swallows the click on the very
      // button it is telling the visitor to press. And fading it to opacity 0 does not
      // give the clicks back: a transparent element still receives them, so one flash
      // would kill that button for the rest of the page's life.
      el.style.cssText =
        "position:fixed;left:50%;bottom:96px;transform:translateX(-50%);z-index:9999;" +
        "pointer-events:none;" +
        "background:#4E7C84;color:#fff;padding:10px 18px;border-radius:9999px;font-size:16px;" +
        "box-shadow:0 6px 20px rgba(0,0,0,.25);font-family:system-ui,sans-serif;max-width:90vw;text-align:center";
      document.body.appendChild(el);
    }
    el.textContent = msg;
    el.style.opacity = "1";
    clearTimeout(el._t);
    el._t = setTimeout(function () { el.style.opacity = "0"; el.style.transition = "opacity .4s"; }, 2600);
  }

  function goDq(file) {
    location.href =
      DQ_PAGE + "?back=" + encodeURIComponent(file) + "&next=" + encodeURIComponent(EXIT_URL);
  }

  // -------------------------------------------------------------------------
  // advance(). Owned by this file for the GENERATED pages (step4 through step14),
  // which carry no inline navigation of their own.
  // -------------------------------------------------------------------------
  function advance() {
    syncConsents();
    capture();
    var file = currentFile();

    // The disqualifier check runs BEFORE validate() on purpose. A disqualifying answer
    // is by definition answered, and gating on a conditional follow-up would make the
    // visitor describe a surgery we are about to bounce them for.
    if (disqualifies(file)) { goDq(file); return; }

    var msg = validate();
    if (msg) { flash(msg); return; }

    var next = nextFor(file);
    if (next) location.href = next;
  }

  // -------------------------------------------------------------------------
  // The gate. Bound to the DOCUMENT in the capture phase, so it lands before any
  // listener bound to the button itself, whatever order the scripts loaded in. That is
  // what lets step3's inline Continue handler stay exactly as it was written.
  //
  // It blocks only when it has something to say. On an unowned page a clean pass falls
  // straight through to the page's own handler.
  // -------------------------------------------------------------------------
  function bindGate() {
    document.addEventListener("click", function (e) {
      var btn = e.target.closest && e.target.closest("#step3Continue, #continueBtn, [data-quiz-continue]");
      if (!btn) return;

      var file = currentFile();
      var isOwned = owned();
      if (!isOwned && !DQ[file] && !consentBoxes().length) return;

      syncConsents();
      capture();

      var stop = function () { e.preventDefault(); e.stopPropagation(); };

      // The disqualifier runs BEFORE validation on purpose, on owned and unowned pages
      // alike. A disqualifying answer is by definition answered.
      if (disqualifies(file)) { stop(); goDq(file); return; }

      var msg = isOwned ? validate() : validateConsents();
      if (msg) { stop(); flash(msg); return; }

      // A generated page has no navigation of its own, so this file supplies it.
      // An unowned page keeps its own, and we have just declined to stop it.
      if (isOwned) {
        stop();
        var next = nextFor(file);
        if (next) location.href = next;
      }
    }, true);
  }

  function bindBack() {
    // Branching means the previous page is only knowable from history: a visitor on
    // step5 came from step4 if female and step3 if not. Let the browser answer.
    var backs = document.querySelectorAll("[data-back]");
    for (var i = 0; i < backs.length; i++) {
      backs[i].addEventListener("click", function (e) {
        e.preventDefault();
        if (history.length > 1) history.back();
        else location.href = "step1.html";
      });
    }
  }

  function bind() {
    restore();
    syncReveals(false);
    syncConsents();
    syncBranchLinks();
    bindExclusive();
    bindBack();
    bindGate();

    document.addEventListener("change", function () {
      capture();
      syncConsents();
      syncBranchLinks();
      // The visitor changed an answer, so a block that just went hidden is stale and
      // its stored text must go with it.
      syncReveals(true);
    }, true);

    document.addEventListener("input", function () {
      syncConsents();
    }, true);

    // A history navigation (back, forward, bfcache) restores the form's values AFTER
    // bind() has already read them, and fires no change or input event. Anything
    // derived from a field therefore has to be recomputed once the restore has landed,
    // which is what pageshow marks.
    window.addEventListener("pageshow", function () {
      restore();
      syncReveals(false);
      syncConsents();
      syncBranchLinks();
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", bind);
  } else {
    bind();
  }
})();
